spring:
  application:
    name: gencheck-gateway-api

  server:
    port: 8080

  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  jackson:
    serialization:
      INDENT_OUTPUT: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Enable CORS for local development
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.gencheck: DEBUG

## JWT Authentication Config (optional)
#security:
#  jwt:
#    secret: your_jwt_secret_key
#    expiration: 86400000 # 1 day in ms
#
## External microservice endpoints
services:
  text-analyzer: http://localhost:5001/analyze-text
  image-analyzer: http://localhost:5002/analyze-image
  video-analyzer: http://localhost:5003/analyze-video

